"""add gst address logo to profile

Revision ID: 974f76ea3e9d
Revises: 23fa7270f8f5
Create Date: 2025-12-01 15:56:41.344519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974f76ea3e9d'
down_revision: Union[str, Sequence[str], None] = '23fa7270f8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('gst_number', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('logo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'logo_url')
    op.drop_column('profiles', 'address')
    op.drop_column('profiles', 'gst_number')
    # ### end Alembic commands ###
